# Generated by Django 3.1 on 2020-08-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('bucket_id', models.AutoField(primary_key=True, serialize=False)),
                ('bucket_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('todo_text', models.CharField(max_length=512)),
                ('is_checked', models.BooleanField(default=False)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.bucket')),
            ],
        ),
    ]
